spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/hyunwoolec
    username: root
    password : paul2858
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        default_batch_fetch_size: 100
#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 2000
logging:
  level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace